version: '3.8'

services:
  easy-penny-recipe:
    image: easy-penny-recipe:0.1.2
    environment:
      - CSS_BASE_URL=${BASE_URL:-http://localhost:3056}
    build: .
    volumes:
      - ./package.json:/community-server/package.json
      - ./data:/data
    ports:
      - "3056:3056"
    restart: unless-stopped

