name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy with Docker Compose
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SERVER_IP << 'EOF'
          echo "START $( date +%y%m%d_%H-%M-%S-%N )" >> /home/pod/github_action.log
        	cd /home/${{secrets.SSH_USERNAME}} 2>> /home/pod/err
          cd easy-penny-recipe || git clone https://github.com/liquid-surf/easy-penny-recipe && cd easy-penny-recipe 2>> /home/pod/err
          git pull 2>> /home/pod/err
          BASE_URL=${{secrets.BASE_URL}} docker-compose up -d --build 2>> /home/pod/err
          echo "STOP $( date +%y%m%d_%H-%M-%S-%N )" >> ./last_github_action.log
        EOF
